// <auto-generated />
using System;
using AcademicDatabaseSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicDatabaseSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250316174722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Course", b =>
                {
                    b.Property<int>("CrsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsID"));

                    b.Property<int?>("CrsDuration")
                        .HasColumnType("int");

                    b.Property<string>("CrsName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<int>("InsID")
                        .HasColumnType("int");

                    b.HasKey("CrsID");

                    b.HasIndex("DeptID");

                    b.HasIndex("InsID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CrsID = 1,
                            CrsDuration = 2,
                            CrsName = "HTML",
                            DeptID = 2,
                            InsID = 3
                        },
                        new
                        {
                            CrsID = 2,
                            CrsDuration = 2,
                            CrsName = "CSS",
                            DeptID = 2,
                            InsID = 3
                        },
                        new
                        {
                            CrsID = 3,
                            CrsDuration = 2,
                            CrsName = "C#",
                            DeptID = 1,
                            InsID = 1
                        },
                        new
                        {
                            CrsID = 4,
                            CrsDuration = 2,
                            CrsName = "OOP",
                            DeptID = 1,
                            InsID = 1
                        },
                        new
                        {
                            CrsID = 5,
                            CrsDuration = 2,
                            CrsName = "SQL",
                            DeptID = 1,
                            InsID = 4
                        },
                        new
                        {
                            CrsID = 6,
                            CrsDuration = 2,
                            CrsName = "OS",
                            DeptID = 1,
                            InsID = 2
                        },
                        new
                        {
                            CrsID = 7,
                            CrsDuration = 2,
                            CrsName = "Network",
                            DeptID = 2,
                            InsID = 2
                        },
                        new
                        {
                            CrsID = 8,
                            CrsDuration = 2,
                            CrsName = "JS",
                            DeptID = 2,
                            InsID = 3
                        },
                        new
                        {
                            CrsID = 9,
                            CrsDuration = 2,
                            CrsName = ".NET",
                            DeptID = 1,
                            InsID = 1
                        },
                        new
                        {
                            CrsID = 10,
                            CrsDuration = 2,
                            CrsName = "AngularJS",
                            DeptID = 3,
                            InsID = 5
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.CourseSession", b =>
                {
                    b.Property<int>("CrsSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsSID"));

                    b.Property<int>("CrsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CrsSID");

                    b.HasIndex("CrsID");

                    b.HasIndex("InsID");

                    b.ToTable("Crs_Sessions");

                    b.HasData(
                        new
                        {
                            CrsSID = 1,
                            CrsID = 1,
                            Date = new DateTime(2020, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 3,
                            Title = "Intro to HTML"
                        },
                        new
                        {
                            CrsSID = 2,
                            CrsID = 2,
                            Date = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 3,
                            Title = "Intro to CSS"
                        },
                        new
                        {
                            CrsSID = 3,
                            CrsID = 3,
                            Date = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 1,
                            Title = "Intro to C#"
                        },
                        new
                        {
                            CrsSID = 4,
                            CrsID = 4,
                            Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 1,
                            Title = "Intro to OOP"
                        },
                        new
                        {
                            CrsSID = 5,
                            CrsID = 5,
                            Date = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 4,
                            Title = "Intro to SQL"
                        },
                        new
                        {
                            CrsSID = 6,
                            CrsID = 10,
                            Date = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 5,
                            Title = "Intro to Angular"
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.CourseSessionAttendance", b =>
                {
                    b.Property<int>("CrsSAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsSAID"));

                    b.Property<int>("CrsSessionID")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.HasKey("CrsSAID");

                    b.HasIndex("CrsSessionID");

                    b.HasIndex("StdID");

                    b.ToTable("CrsSessionAtts");

                    b.HasData(
                        new
                        {
                            CrsSAID = 1,
                            CrsSessionID = 1,
                            Notes = "",
                            StdID = 1
                        },
                        new
                        {
                            CrsSAID = 2,
                            CrsSessionID = 2,
                            Notes = "",
                            StdID = 1
                        },
                        new
                        {
                            CrsSAID = 3,
                            CrsSessionID = 3,
                            Notes = "",
                            StdID = 1
                        },
                        new
                        {
                            CrsSAID = 4,
                            CrsSessionID = 5,
                            Notes = "",
                            StdID = 2
                        },
                        new
                        {
                            CrsSAID = 5,
                            CrsSessionID = 4,
                            Notes = "",
                            StdID = 2
                        },
                        new
                        {
                            CrsSAID = 6,
                            CrsSessionID = 1,
                            Notes = "",
                            StdID = 3
                        },
                        new
                        {
                            CrsSAID = 7,
                            CrsSessionID = 2,
                            Notes = "",
                            StdID = 4
                        },
                        new
                        {
                            CrsSAID = 8,
                            CrsSessionID = 6,
                            Notes = "",
                            StdID = 4
                        },
                        new
                        {
                            CrsSAID = 9,
                            CrsSessionID = 6,
                            Notes = "",
                            StdID = 5
                        },
                        new
                        {
                            CrsSAID = 10,
                            CrsSessionID = 3,
                            Notes = "",
                            StdID = 5
                        },
                        new
                        {
                            CrsSAID = 11,
                            CrsSessionID = 2,
                            Notes = "",
                            StdID = 5
                        },
                        new
                        {
                            CrsSAID = 12,
                            CrsSessionID = 1,
                            Notes = "",
                            StdID = 5
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Department", b =>
                {
                    b.Property<int>("Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dept_ID"));

                    b.Property<string>("Dept_Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dept_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("Dept_ID");

                    b.HasIndex("ManagerID")
                        .IsUnique()
                        .HasFilter("[ManagerID] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Dept_ID = 1,
                            Dept_Location = "Ismailia Branch Building, 2nd Floor",
                            Dept_Name = "SD"
                        },
                        new
                        {
                            Dept_ID = 2,
                            Dept_Location = "Ismailia Branch Building, 2nd Floor",
                            Dept_Name = "UI"
                        },
                        new
                        {
                            Dept_ID = 3,
                            Dept_Location = "Ismailia Branch Building, 2nd Floor",
                            Dept_Name = "MAD"
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Instructor", b =>
                {
                    b.Property<int>("InsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsID"));

                    b.Property<int?>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("InsFName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InsLName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InsID");

                    b.HasIndex("Dept_ID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InsID = 1,
                            Dept_ID = 1,
                            InsFName = "Mohamed",
                            InsLName = "Tharwat",
                            Phone = "01016297668",
                            Salary = 5000m
                        },
                        new
                        {
                            InsID = 2,
                            Dept_ID = 1,
                            InsFName = "Mohamed",
                            InsLName = "Hatem",
                            Phone = "01004190041",
                            Salary = 7500m
                        },
                        new
                        {
                            InsID = 3,
                            Dept_ID = 2,
                            InsFName = "Mai",
                            InsLName = "Moustafa",
                            Phone = "01550507768",
                            Salary = 4800m
                        },
                        new
                        {
                            InsID = 4,
                            Dept_ID = 1,
                            InsFName = "Rami",
                            InsLName = "Mohamed",
                            Phone = "01010556101",
                            Salary = 6000m
                        },
                        new
                        {
                            InsID = 5,
                            Dept_ID = 2,
                            InsFName = "Hala",
                            InsLName = "Nazmy",
                            Phone = "01004117122",
                            Salary = 8000m
                        },
                        new
                        {
                            InsID = 6,
                            Dept_ID = 3,
                            InsFName = "Asmaa",
                            InsLName = "Gomaa",
                            Phone = "01100488122",
                            Salary = 8000m
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.StdCrs", b =>
                {
                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.Property<int>("CrsID")
                        .HasColumnType("int");

                    b.HasKey("StdID", "CrsID");

                    b.HasIndex("CrsID");

                    b.ToTable("Std_Courses");

                    b.HasData(
                        new
                        {
                            StdID = 1,
                            CrsID = 1
                        },
                        new
                        {
                            StdID = 1,
                            CrsID = 2
                        },
                        new
                        {
                            StdID = 1,
                            CrsID = 3
                        },
                        new
                        {
                            StdID = 2,
                            CrsID = 5
                        },
                        new
                        {
                            StdID = 2,
                            CrsID = 4
                        },
                        new
                        {
                            StdID = 3,
                            CrsID = 1
                        },
                        new
                        {
                            StdID = 4,
                            CrsID = 10
                        },
                        new
                        {
                            StdID = 4,
                            CrsID = 6
                        },
                        new
                        {
                            StdID = 5,
                            CrsID = 6
                        },
                        new
                        {
                            StdID = 5,
                            CrsID = 7
                        },
                        new
                        {
                            StdID = 5,
                            CrsID = 2
                        },
                        new
                        {
                            StdID = 5,
                            CrsID = 1
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Student", b =>
                {
                    b.Property<int>("St_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("St_ID"));

                    b.Property<string>("St_FName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("St_LName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("St_Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("St_ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            St_ID = 1,
                            St_FName = "Basem",
                            St_LName = "Mohamed",
                            St_Phone = "01016297668"
                        },
                        new
                        {
                            St_ID = 2,
                            St_FName = "Amr",
                            St_LName = "Hany",
                            St_Phone = "01542197951"
                        },
                        new
                        {
                            St_ID = 3,
                            St_FName = "Alaa",
                            St_LName = "Eisa",
                            St_Phone = "01111190922"
                        },
                        new
                        {
                            St_ID = 4,
                            St_FName = "Hany",
                            St_LName = "Abdou",
                            St_Phone = "01004190041"
                        },
                        new
                        {
                            St_ID = 5,
                            St_FName = "Omar",
                            St_LName = "Al-Araby",
                            St_Phone = "01204144070"
                        },
                        new
                        {
                            St_ID = 6,
                            St_FName = "Mohamed",
                            St_LName = "Hisham",
                            St_Phone = "01100488122"
                        },
                        new
                        {
                            St_ID = 7,
                            St_FName = "Mahmoud",
                            St_LName = "Ahmed",
                            St_Phone = "01010556101"
                        },
                        new
                        {
                            St_ID = 8,
                            St_FName = "Karim",
                            St_LName = "Helmy",
                            St_Phone = "01550507768"
                        },
                        new
                        {
                            St_ID = 9,
                            St_FName = "Basem",
                            St_LName = "Atia",
                            St_Phone = "01100557030"
                        },
                        new
                        {
                            St_ID = 10,
                            St_FName = "Mohamed",
                            St_LName = "Abdelwahab",
                            St_Phone = "01004117122"
                        });
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Course", b =>
                {
                    b.HasOne("AcademicDatabaseSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicDatabaseSystem.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.CourseSession", b =>
                {
                    b.HasOne("AcademicDatabaseSystem.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CrsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicDatabaseSystem.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InsID");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.CourseSessionAttendance", b =>
                {
                    b.HasOne("AcademicDatabaseSystem.Models.CourseSession", "CrsSID")
                        .WithMany("CrsSA")
                        .HasForeignKey("CrsSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicDatabaseSystem.Models.Student", "Student")
                        .WithMany("CrsSAs")
                        .HasForeignKey("StdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrsSID");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Department", b =>
                {
                    b.HasOne("AcademicDatabaseSystem.Models.Instructor", "InstructorsMng")
                        .WithOne("ManagedAt")
                        .HasForeignKey("AcademicDatabaseSystem.Models.Department", "ManagerID");

                    b.Navigation("InstructorsMng");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Instructor", b =>
                {
                    b.HasOne("AcademicDatabaseSystem.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_ID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.StdCrs", b =>
                {
                    b.HasOne("AcademicDatabaseSystem.Models.Course", "Course")
                        .WithMany("Std_Courses")
                        .HasForeignKey("CrsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicDatabaseSystem.Models.Student", "Student")
                        .WithMany("Std_Courses")
                        .HasForeignKey("StdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Std_Courses");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.CourseSession", b =>
                {
                    b.Navigation("CrsSA");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("ManagedAt");
                });

            modelBuilder.Entity("AcademicDatabaseSystem.Models.Student", b =>
                {
                    b.Navigation("CrsSAs");

                    b.Navigation("Std_Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
